from .port import ReservationRepository, StudentRepository, SeatRepository
from .model import TimePeriod, Position


class ReservationService:
    def __init__(self, repository: ReservationRepository) -> None: ...
    def reserve(self, student_id: str, time_period: TimePeriod, seat_position: Position) -> None: ...
    def check_in(self, id: str) -> None: ...
    def cancel(self, id: str) -> None: ...
    def end(self, id: str) -> None: ...
    def extend_time_period(self, id: str, second: int) -> None: ...
    def countdown_begin(self, id: str) -> None: ...
    def countdown_end(self, id: str) -> None: ...


class StudentService:
    def __init__(self, repository: StudentRepository) -> None: ...
    def add_reputation_score(self, id: str, value: int) -> None: ...
    def reduce_reputation_score(self, id: str, value: int) -> None: ...
    def add_reservation(self, student_id: str, reservation_id: str) -> None: ...
    def delete_reservation(self, student_id: str, reservation_id: str) -> None: ...


class SeatService:
    def __init__(self, repository: SeatRepository) -> None: ...
    def occupy(self, position: Position) -> None: ...
    def unoccupy(self, position: Position) -> None: ...
    def maintain(self, position: Position) -> None: ...
    def fix(self, position: Position) -> None: ...


# TODO: 加上@Command
class StudentSeatReservationService:
    def __init__(
        self, reservation_service: ReservationService, student_service: StudentService, seat_service: SeatService
    ) -> None: ...
    def reserve(self, student_id: str, time_period: TimePeriod, seat_position: Position) -> None: ...
    def check_in(self, reservation_id: str) -> None: ...
    def extend_time_period(self, reservation_id: str, time: int) -> None: ...
    def temporarily_away(self, reservation_id: str) -> None: ...
    def return_from_away(self, reservation_id: str) -> None: ...
    def reserve_undo(self, student_id: str, time_period: TimePeriod, seat_position: Position) -> None: ...
    def check_in_undo(self, reservation_id: str) -> None: ...
    def extend_time_period_undo(self, reservation_id: str, time: int) -> None: ...
    def temporarily_away_undo(self, reservation_id: str) -> None: ...
    def return_from_away_undo(self, reservation_id: str) -> None: ...
