---
config:
  layout: elk
  class:
    hideEmptyMembersBox: true
---
%% 场景： 大学图书馆/自习室，学生可以预约座位、签到、暂离、续约。
%% 业务规则：
%% - 座位分区域（静音区/讨论区/电脑区）
%% - 预约时段最小 1h，最长 4h
%% - 预约后 30 分钟内不签到 → 自动取消 + 扣信用分
%% - 暂离最长 30 分钟，超时自动释放座位
%% - 信用分 < 60 → 本周不能再预约
%% - 管理员可以设置座位维护状态
classDiagram
direction LR
	namespace Model {
    class ReputationScore {
      <<@dataclass(frozen=True, slots=True)>>
      value: int
      %% 校验：value∈[0,100]
      add_score(self) ReputationScore
      reduce_score(self) ReputationScore
      can_reservation(self) bool
      %% 信用分 < 60 → 不能预约
    }

    class Student {
      <<@dataclass(kw_only=True, slots=True)>>
      id: str
      name: str
      %% 校验：教务系统中看看有没有这个学生
      %% 没有单独分出来StudentId这个类来做数据校验
      %% 因为name需要和id联合校验
      reputation_score: ReputationScore = ReputationScore(100)
      %% 加上@property，直接返回reputation_score.value
      %% __eq__和__hash__都用id
    }

    class SeatStatus {
      <<Enum>>
      AVAILABLE / OCCUPIED / MAINTAIN
    }

    class ReservationStatus {
      <<Enum>>
      PENDING_CHECK_IN / CHECKED_IN / ENDED / EXPIRED / CANCELLED
    }

    class SeatType {
      <<Enum>>
      QUIET / DISCUSSION / COMPUTER
    }

    class Position {
      <<@dataclass(frozen=True, slots=True)>>
      row: int
      column: int 
    }

    class TimePeriod {
      <<@dataclass(frozen=True, slots=True)>>
      from_time: datetime
      to_time: datetime
      extend_time_period(self, to: datetime) TimePeriod
      %% 校验：from ≤ to，预约时段最小 1h，最长 4h
    }

    class Reservation {
      <<@dataclass(kw_only=True, slots=True)>>
      id: int
      student_id: str
      timer_id: int
      %% 需要从预约能查到学生，也需要从学生能查到预约
      %% 此处student_id不需要校验，因为是由校验过的学生创建的
      time_period: TimePeriod
      seat_position: Position
      status: ReservationStatus = ReservationStatus.PENDING_CHECK_IN
      temporarily_away_available_time: int = 1800
      %% 直接用秒数就足够了
      %% 当然不应该直接这样写，最好是用配置文件

      check_in(self) None
      cancel(self) None
      end(self) None
      %% 状态机轮转，等我画状态图
      %% 在Service层编排
      %% __eq__和__hash__都用id
    }

    class Seat {
      <<@dataclass(kw_only=True, slots=True)>>
      status: SeatStatus = AVAILABLE
      type: SeatType
      position: Position
      %% 实际上座位不知道自己是什么类型，不知道自己在哪里
      %% 但是这里这样写也不是不行，直接看成元组得了

      occupy(self) None
      unoccupy(self) None
      %% 在Service层编排
      %% __eq__和__hash__都用position
    }
	}

  Position --> Reservation
  ReputationScore --> Student
  ReservationStatus --> Reservation
  TimePeriod --> Reservation
  Student --> Reservation
  Seat --> Reservation
  Position --> Seat
  SeatStatus --> Seat
  SeatType --> Seat

  namespace Ports {
    class StudentRepository {
      <<ABC>>
      save(self, student: Stduent) None
      get_by_id(self, student: Student) Student | None
      get_all(self) list[Student]
    }

    class SeatRepository {
      <<ABC>>
      save(self, seat: Seat) None
      get_by_position(self, position: Position) Seat | None
      get_all(self) list[Seat]
    }

    class ReservationRepository {
      <<ABC>>
      save(self, reservation: Reservation) None
      get_by_id(self, id: str) Reservation | None
      get_by_student(self, student: Student) list[Reservation]
      get_by_seat(self, seat: Seat) list[Reservation]
      get_by_time_period(self, time_period: TimePeriod) list[Reservation]
      get_all(self) list[Reservation]
    }
  }

  Student ..> StudentRepository
  Position ..> SeatRepository
  Seat ..> SeatRepository
  TimePeriod ..> ReservationRepository
  Reservation ..> ReservationRepository

  namespace Service {
    class ReservationService {
      _repository: ReservationRepository
      _event_bus: EventBus
      
      __init__(self, repository: ReservationRepository, event_bus: EventBus) None
      reserve(self, student_id: str, time_period: TimePeriod, seat_position: Position) None
      %% 实际应该是用户处于登录状态才能使用，自动传入student_id
      %% 用一下countdown_begin()
      %% 比如每隔10分钟，更新一下距离签到的时间
      %% 然后结束时间设置为签到时间+30分钟，结束的时候去扣信誉分
      %% check_in提前中断计时
      %% 等会，用户离场全靠自觉吗？？？🫠🫠🫠
      %% 还是用计时器，到时间了自动释放座位吧。这样下一个人来了就把上一个人赶走了
      %% 同一个预约单只能同时存在一个计时器，这是合理的
      %% 因为没签到前不可能暂离
      %% 当然这部分的维护交给状态机，还需要定义对应的异常

      check_in(self, id: str) None
      %% 中断计时器
      cancel(self, id: str) None
      end(self, id: str) None
      extend_time_period(self, id: str, time: int) None
      %% 这几个本来想publish一个UpdateView事件的，但是没必要，前端负责这部分
      countdown_begin(self, id: str) None
      %% 这里的形参要加上Timer的那一堆参数
      %% Timer()开始计时
      
      %% 之前的方法名是temporarily_waay
      %% 但是我感觉在单独的Service里面还是先控制好结合具体语境的程度
      %% 到了StudentSeatReservationService里面再考虑用暂时离场/离场返回这种说法
      %% 虽然这两个方法目前也不需要跨领域编排，但是还是要注意方法名，尽可能专注于目前的服务
      countdown_end(self, id: str) None
      %% 中断计时器，这里还没写完
    }

    class StudentService {
      _repository: StudentRepository

      __init__(self, repository: StudentRepository) None
      %% update_reputation_score(self, id: str, reputation_score: ReputationScore) None
      %% reputation_score的增加是一个异步的周期任务
      %% 当reputation_score减少时，publish一个ReduceReputationScore
      %% 但是这样写也就意味着不能直接指定修改多少
      %% 所以此处直接传入属性值而不是值对象
      add_reputation_score(self, id: str, value: int) None
      reduce_reputation_score(self, id: str, value: int) None
      add_reservation(self, student_id: str, reservation_id: str) None
      delete_reservation(self, student_id: str, reservation_id: str) None
    }

    class SeatService {
      _repository: SeatRepository

      __init__(self, repository: SeatRepository) None
      occupy(self, position: Position) None
      unoccupy(self, position: Position) None
      maintain(self, position: Position) None
      fix(self, position: Position) None
    }

    class StudentSeatReservationService {
      <<@Command>>
      _reservation_service: ReservationService
      _student_service: StudentService
      _seat_service: SeatService

      __init__(self, reservation_service: ReservationService, student_service: StudentService, seat_service: SeatService) None
      reserve(self, student_id: str, time_period: TimePeriod, seat_position: Position) None
      check_in(self, reservation_id: str) None
      extend_time_period(self, reservation_id: str, time: int) None
      temporarily_away(self, reservation_id: str) None
      return_from_away(self, reservation_id: str) None
      %% 因为被Command装饰，所以要提供对应的undo方法
      reserve_undo(self, student_id: str, time_period: TimePeriod, seat_position: Position) None
      check_in_undo(self, reservation_id: str) None
      extend_time_period_undo(self, reservation_id: str, time: int) None
      temporarily_away_undo(self, reservation_id: str) None
      return_from_away_undo(self, reservation_id: str) None
      %% 其他的Service里面不用加undo了，这里统一处理就够了
    }
  }

  %% EventBus --> ReservationService
  ReservationRepository --> ReservationService
  TimePeriod ..> ReservationService
  Position ..> ReservationService
  Reservation ..> ReservationService

  %% EventBus --> StudentService
  StudentRepository --> StudentService
  Student ..> StudentService
  ReputationScore ..> StudentService

  %% EventBus --> SeatService
  StudentRepository --> SeatService
  Position ..> SeatService

  ReservationService --> StudentSeatReservationService
  SeatService --> StudentSeatReservationService
  StudentService --> StudentSeatReservationService

  ReservationService ..> StudentSeatReservationService
  StudentService ..> StudentSeatReservationService
  SeatService ..> StudentSeatReservationService

  %% namespace Event {
  %%   class ReservationCreatedEvent {
  %%     id: str
  %%     student_id: str 
  %%     time_period: TimePeriod
  %%     seat_position: Position
  %%     status: ReservationStatus
  %%   }
    
  %%   class ReservationCreatedTimeOutEvent {
  %%     id: str
  %%     student_id: str
  %%     time_period: TimePeriod
  %%     seat_position: Position
  %%     status: ReservationStatus
  %%     now_time: datetime = time.now()
  %%   }

  %%   class InsufficientReputationScoreEvent {
  %%     id: str
  %%     name: str
  %%     reputation_score: ReputationScore
  %%   }

  %%   class TemporarilyAwayEvent {
  %%     id: str
  %%     temporarily_away_available_time: int
  %%     %% 接到这个事件的开始倒计时
  %%     %% 倒计时结束后，自动释放座位并标记预约单为已超时
  %%     %% 然后扣除信誉分
  %%   }

  %%   class ReduceReputationScore {
  %%     id: str
  %%     reputation_score: ReputationScore
  %%   }

  %%   %% 虽然有一些已经有相关的Exception了
  %%   %% 但是我觉得Exception只应该负责记录错误日志，不负责输出
  %%   %% 所以还需要有相应的Event来负责输出
  %% }

  namespace Infrastructure {
    class MemoryStudentRepository {
      _students: dict[str, Student]
      save(self, student: Student) None
      get_by_id(self, student: Student) Student | None
      get_all(self) list[Student]
    }

    class MemorySeatRepository {
      _seats: dict[tuple[int, int], Seat]
      save(self, seat: Seat) None
      get_by_position(self, position: Position) Seat | None
      get_all(self) list[Seat]
    }

    class MemoryReservationRepository {
      _reservations: dict[str, Reservation]
      save(self, reservation: Reservation) None
      get_by_id(self, id: str) Reservation | None
      get_by_student(self, student: Student) list[Reservation]
      get_by_seat(self, seat: Seat) list[Reservation]
      get_by_time_period(self, time_period: TimePeriod) list[Reservation]
      get_all(self) list[Reservation]
    }

    %% 根本用不上事件总线……
    %% class EventBus {
    %%   <<ABC>>
    %%   _handlers: dict[type, list[Callable]] = defaultdict(list)

    %%   register(self, event_type: type, handler: Callable) None
    %%   publish(self, event: object) None
    %% }

    class Timer {
      <<@dataclass(frozen=True, slots=True)>>

      id: int
      %% 和Reservation关联
      scan_cycle: int = 30
      waiting_time: int
      time_based_trigger: Callable[[dict],None] = lambda: None
      time_based_parameter: dict[str,Any]
      final_trigger: Callable[[dict],None] = lambda: None
      final_parameter: dict[str,Any]
      can_continue: bool = False

      __init__(
        self, 
        scan_cycle: int,
        waiting_time: int,
        time_based_trigger: Callable[[dict],None] = lambda: None, 
        time_based_parameter: dict[str,Any],
        interrupt_trigger: Callable[[dict],None] = lambda: None, 
        interrupt_parameter: dict[str,Any],
        final_trigger: Callable[[dict],None] = lambda: None, 
        final_parameter: dict[str,Any]
      ) None
      scan(self) None
      %% 等待scan_cycle秒后，调用self.time_based_trigger(self.time_based_parameter)
      %% 当waiting_time秒后，调用self.final_trigger(self.final_parameter)
      %% 若can_continue == False，则提前终止并调用self.interrupt_trigger(self.interrupt_parameter)
      interrupt(self) None
    }
    %% Timmer与其他类的关系还没画

    class Command {
      %% 用Command类装饰StudentSeatReservationService，调用方全程无感
      cls: type
      command_list: list[Callable[[None],Callable]]

      __init__(self, cls) None
      __call__(self, *args, **kwargs) Command
      %% 把全部不以_开头的方法setattr到_push装饰器
      _push(self, func: Callable[[None],Callable]) None
      %% 这是一个装饰器
      %% 对于每一个函数，先执行，若有异常，则回滚command_list中的全部内容
      %% 当然这需要每一个函数都有对应的撤销方法，命名为原函数名_undo
      %% 若无异常，则将原函数名_undo加入command_list中
      %% 为了保留undo的参数，需要用lambda进行包装
    }
  }

  StudentRepository ..|> MemoryStudentRepository
  Position ..> MemorySeatRepository
  SeatRepository ..|> MemorySeatRepository
  ReservationRepository ..|> MemoryReservationRepository
  TimePeriod ..> MemoryReservationRepository
  %% Student --> MemoryStudentRepository
  %% Seat --> MemorySeatRepository
  %% Reservation --> MemoryReservationRepository
  Command --> StudentSeatReservationService

  namespace Exception {
    class DomainError {}

    class InfrastructureError {}

    class InvalidReservationStateError {
      __init__(self, info: str, status_from: Any, status_to: Any) None
    }

    class InvalidSeatStateError {
      __init__(self, info: str, status_from: Any, status_to: Any) None
    }

    class ReputationScoreOutOfRangeError {
      __init__(self, info: str, reputation_score: ReputationScore, to: int)
      %% 理论上还需要给上student_id才行，但这里reputation_score是不知道student的
      %% 所以不加了
    }

    class DatabaseConnectionError {__init__(self, info: str)}
    class PersistenceError {__init__(self, info: str)}
    class DataIntegrityError {__init__(self, info: str)}

    class MissingConfigurationError {__init__(self, info: str)}
    class InvalidConfigurationError {__init__(self, info: str)}
    %% 这两个可以使用配置默认值
    %% 当然如果是后端数据库密码这种默认值也救不了的话，直接exit得了
    %% 对于前端使用者来说默认值救不了的话，拒绝访问就可以了

    class ExternalServiceUnavailableError {__init__(self, info: str)}
    class ExternalServiceError {__init__(self, info: str)}
    %% 我还不太清楚这些基础设施层系统故障要携带什么上下文，以后可能会加上
  }
  %% DomainError给个WARNNING就行了
  %% InfrastructureError视情况ERROR/CRITICAL，然后还要考虑运维告警与优雅降级

  DomainError --|> InvalidReservationStateError
  DomainError --|> InvalidSeatStateError
  DomainError --|> ReputationScoreOutOfRangeError

  InfrastructureError --|> DatabaseConnectionError
  InfrastructureError --|> PersistenceError
  InfrastructureError --|> DataIntegrityError
  InfrastructureError --|> MissingConfigurationError
  InfrastructureError --|> InvalidConfigurationError
  InfrastructureError --|> ExternalServiceUnavailableError
  InfrastructureError --|> ExternalServiceError